### ISSUE TITLE
Why is this obfuscated?

### ISSUE THREAD

**Issue by zLeki** [TurfuFrogy/EzNotifier#2]
Why would you put obfuscated code on GitHub. A place where developers share code if we cannot see your code. This could also be a user security issue. Could you please un-obfuscate your code?

**Comment by TurfuFrogy** [comment]
You're the guy who came in my Discord server and created a ticket to ask me how I bypass cloudflare so please stfu. We both know why you opened this GitHub issue.

Have a nice day.

**Comment by zLeki** [comment]
Never answered the question

**Comment by TurfuFrogy** [comment]
> Never answered the question

Hey, I don't care 😘
